const mongoose = require('mongoose');

const archiveSchema = new mongoose.Schema(
  {
    organizationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Organization",
      default: null,
      index: true,
    },
    originalFormId: { type: mongoose.Schema.Types.ObjectId, ref: 'Form' },
    srNo: { type: String, required: true },
    name: { type: String, required: true },
    joiningDate: { type: Date },
    propertyType: {
      type: String,
      enum: ["bed", "room", "shop"],
      default: "bed",
      index: true,
    },
    category: { type: String },
    roomId: { type: String },
    roomNo: { type: String },
    depositAmount: { type: Number },
    phoneNo : {type: Number},
    intakeStatus: {
      type: String,
      enum: ["submitted", "pending_tenant"],
      default: "submitted",
      index: true,
    },
    address: { type: String },
    pincode: { type: String },
    city: { type: String },
    state: { type: String },
    houseNo: { type: String },
    nearbyPlace: { type: String },
    relativeAddress1: { type: String },
    relativeAddress2: { type: String },
    relative1Relation: { type: String },
    relative1Name: { type: String },
    relative1Phone: { type: String },
    relative2Relation: { type: String },
    relative2Name: { type: String },
    relative2Phone: { type: String },
    floorNo: { type: String },
    bedNo: { type: String },
    familyMembers: { type: Number, default: 0 },
    shopName: { type: String },
    shopBusiness: { type: String },
    companyAddress: { type: String },
    dateOfJoiningCollege: { type: Date },
    dob: { type: Date },
    baseRent: { type: Number },
    firstRentStatus: { type: String },
    firstRentMonth: { type: String },
    rentHistory: { type: [mongoose.Schema.Types.Mixed], default: [] },
    documents: { type: [mongoose.Schema.Types.Mixed], default: [] },
    shiftEffectiveFrom: { type: Date },
    rents: [
      {
        rentAmount: { type: Number },
        date: { type: Date },
        month: { type: String },
        paymentMode: { type: String },
        utr: { type: String },
        note: { type: String },
        receiptUrl: { type: String },
        payments: { type: [mongoose.Schema.Types.Mixed], default: [] },
      },
    ],
    paymentAudit: { type: [mongoose.Schema.Types.Mixed], default: [] },
    leaveDate: { type: String },
    leaveSettlement: {
      deductFromDeposit: { type: Boolean, default: false },
      selectedMonths: [{ type: String }],
      deductions: [
        {
          month: { type: String },
          amount: { type: Number, default: 0 },
          days: { type: Number, default: 0 },
          dailyRent: { type: Number, default: 0 },
          cycleRange: { type: String, default: "" },
        },
      ],
      grossDeposit: { type: Number, default: 0 },
      totalDeduction: { type: Number, default: 0 },
      refundableDeposit: { type: Number, default: 0 },
      amountDueFromTenant: { type: Number, default: 0 },
      note: { type: String, default: "" },
    },
  });

archiveSchema.index({ organizationId: 1, leaveDate: 1 });

module.exports = mongoose.model('Archive', archiveSchema);
